name: Lint Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: sigstore/cosign-installer@bb61838e7ee5bf314f85f2e219b3706835fa6306 # pin@v2.2.0

      - name: Set up Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # pin@v1.1
        with:
          version: v3.8.1

      - uses: actions/setup-python@v3 # pin@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@09ed88797198755e5031f25be13da255e7e33aad # pin@v2.2.1

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: "Add NGINX Ingress Repository"
        run: |
          helm repo add ingress-nginx "https://kubernetes.github.io/ingress-nginx"
          helm repo update

      - name: Create KIND Cluster
        uses: helm/kind-action@94729529f85113b88f4f819c17ce61382e6d8478 # pin@v1.2.0

      - name: Install Ingress Controller
        run: "helm install ingress-nginx/ingress-nginx --generate-name --set controller.service.type='NodePort' --set controller.admissionWebhooks.enabled=false"

      - name: Run chart-testing (install)
        run: ct install --config ct-install.yaml
